create table if not exists public.early_access (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  country text not null,
  role text not null,
  created_at timestamptz not null default now()
);

alter table public.early_access
  add column if not exists full_name text,
  add column if not exists email text,
  add column if not exists country text,
  add column if not exists role text,
  add column if not exists created_at timestamptz default now();

create index if not exists early_access_created_at_idx
  on public.early_access (created_at desc);

create index if not exists early_access_email_lookup_idx
  on public.early_access (email);

alter table public.early_access enable row level security;
revoke all on table public.early_access from anon, authenticated;

comment on table public.early_access is
  'Private beta signup records. Public clients have no direct table policy; writes go through the server route.';

do $$
begin
  if to_regclass('public.waitlist') is not null then
    execute $migration$
      insert into public.early_access (full_name, email, country, role, created_at)
      select
        w.full_name,
        lower(w.email),
        w.country,
        coalesce(w.user_type, 'Traveler'),
        coalesce(w.created_at, now())
      from public.waitlist w
      where not exists (
        select 1
        from public.early_access ea
        where lower(ea.email) = lower(w.email)
      )
    $migration$;
  end if;
end
$$;
